name: Cherry-pick a release

on:
  workflow_dispatch:
    inputs:
      amp-version:
        description: AMP version (13 digits)
        required: true
        type: string
      shas:
        description: commit sha(s) to cherry-pick with (i.e. abcdef1 abcdef2)
        required: true
        type: string

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    environment: cherry-pick

    steps:
      - name: Checkout ampproject/amphtml
        uses: actions/checkout@v2
        with:
          repository: ampproject/amphtml
          fetch-depth: 0
          token: ${{ secrets.AMPPROJECTBOT }}

      - name: Set git config
        run: |
          NAME=$(git --no-pager log --format=format:'%an' -n 1)
          EMAIL="$(git --no-pager log --format=format:'%ae' -n 1)"
          git config --global user.name $NAME
          git config --global user.email $EMAIL

      - name: Cherry-pick ${{ github.event.inputs.amp-version }} with ${{ github.event.inputs.shas }}
        run: |
          git checkout -b cherry-pick-${{ github.event.inputs.amp-version }} ${{ github.event.inputs.amp-version }}
          git cherry-pick -x ${{ github.event.inputs.shas }}
          git push --set-upstream https://github.com/ampproject/amphtml.git cherry-pick-${{ github.event.inputs.amp-version }}

  get-channels-to-promote:
    needs: cherry-pick

    runs-on: ubuntu-latest

    outputs:
      channels: ${{ steps.get-channels.outputs.channels }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Get channels with ${{ github.event.inputs.amp-version }}
        id: get-channels
        run: |
          CHANNELS=$(npx ts-node ./scripts/get-channels --amp_version=${{ github.event.inputs.amp-version }})
          echo "::set-output name=channels::"$CHANNELS""

  promote-beta-opt-in:
    needs: get-channels-to-promote
    if: contains(needs.get-channels-to-promote.outputs.channels, 'beta-opt-in')
    uses: ampproject/cdn-configuration/.github/workflows/promote-beta-experimental-opt-in.yml@main
    with:
      amp-version: ${{ github.event.inputs.amp-version }}

  promote-beta-traffic:
    needs: get-channels-to-promote
    if: contains(needs.get-channels-to-promote.outputs.channels, 'beta-traffic')
    uses: ampproject/cdn-configuration/.github/workflows/promote-beta-experimental-traffic.yml@main
    with:
      amp-version: ${{ github.event.inputs.amp-version }}

  promote-stable:
    needs: get-channels-to-promote
    if: contains(needs.get-channels-to-promote.outputs.channels, 'stable')
    uses: ampproject/cdn-configuration/.github/workflows/promote-stable.yml@main
    with:
      amp-version: ${{ github.event.inputs.amp-version }}

  promote-lts:
    needs: get-channels-to-promote
    if: contains(needs.get-channels-to-promote.outputs.channels, 'lts')
    uses: ampproject/cdn-configuration/.github/workflows/promote-lts.yml@main
    with:
      amp-version: ${{ github.event.inputs.amp-version }}
