name: Cherry-pick a release

on:
  workflow_dispatch:
    inputs:
      amp-version:
        description: AMP version (13 digits)
        required: true
        type: string
      shas:
        description: commit sha(s) to cherry-pick with (i.e. abcdef1 abcdef2)
        required: true
        type: string

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    environment: cherry-pick

    steps:
      - name: Checkout ampproject/amphtml
        uses: actions/checkout@v2
        with:
          repository: ampproject/amphtml
          fetch-depth: 0
          token: ${{ secrets.AMPPROJECTBOT }}

      - name: Generate cherry-pick branch name
        run: |
          AMP_VERSION=${{ github.event.inputs.amp-version }}
          read -r -a SHAS_ARRAY <<< "${{ github.event.inputs.shas }}"
          SHAS_COUNT=${#SHAS_ARRAY[@]}
          CURRENT_CP_COUNT=${AMP_VERSION:10:13}
          NEW_CP_COUNT=00$(expr $CURRENT_CP_COUNT + $SHAS_COUNT)
          CHERRY_PICK_BRANCH=amp-release-${AMP_VERSION:0:10}${PADDED_CP_COUNT: -3}
          echo $CHERRY_PICK_BRANCH

      - name: Set git config
        run: |
          NAME=$(git --no-pager log --format=format:'%an' -n 1)
          EMAIL="$(git --no-pager log --format=format:'%ae' -n 1)"
          git config --global user.name $NAME
          git config --global user.email $EMAIL

      - name: Cherry-pick ${{ github.event.inputs.amp-version }} with ${{ github.event.inputs.shas }}
        run: |
          git cherry-pick -x ${{ github.event.inputs.shas }}
          git checkout -b $CHERRY_PICK_BRANCH ${{ github.event.inputs.amp-version }}
          git push --set-upstream https://github.com/ampproject/amphtml.git $CHERRY_PICK_BRANCH

      # TODO(estherkim): tie to promote workflow
